// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cugmawrlgwkxvtzdyzki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1Z21hd3JsZ3dreHZ0emR5emtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Njg1NzIsImV4cCI6MjA1NzE0NDU3Mn0.vAqz_HAbLKsClXz1qJ4POGnMayNlJPMchVBDnt36zzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);